<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-module</artifactId>
        <version>1.1.8.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-components</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>spring-boot-starter-log</module>
        <module>spring-boot-starter-data</module>
        <module>spring-boot-starter-generator</module>
        <module>spring-boot-starter-file</module>
        <module>spring-boot-starter-cms</module>
        <module>spring-boot-starter-dict</module>
        <module>spring-boot-starter-im</module>
        <module>spring-boot-starter-ocr</module>
        <module>spring-boot-starter-finance</module>
        <module>spring-boot-starter-trade</module>
        <module>spring-boot-starter-wechat</module>
        <module>spring-boot-starter-sms</module>
        <module>spring-boot-starter-excel</module>
        <module>spring-boot-starter-system</module>
        <module>spring-boot-starter-contract</module>
        <module>spring-boot-starter-web</module>
        <module>spring-boot-starter-security</module>
        <module>spring-boot-starter-cache</module>
        <module>spring-boot-starter-job</module>
    </modules>
</project>