<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-module</artifactId>
       <version>3.5.3</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-components</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>TG-boot组件模块聚合，提供通用能力</description>
    <url>https://github.com/modulepub/tg-boot.git</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
            <comments>Permissive open source license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>panzhen</id>
            <name>panzhen</name>
            <email>panzhen@mail.module.pub</email>
            <url>https://github.com/modulepub/tg-boot.git</url>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git@github.com:modulepub/tg-boot.git</connection>
        <developerConnection>scm:git@github.com:modulepub/tg-boot.git</developerConnection>
        <url>https://github.com/modulepub/tg-boot.git</url>
        <tag>3.5.3</tag>
    </scm>

    <modules>
        <module>spring-boot-starter-log</module>
        <module>spring-boot-starter-data</module>
        <module>spring-boot-starter-generator</module>
        <module>spring-boot-starter-file</module>
        <module>spring-boot-starter-cms</module>
        <module>spring-boot-starter-dict</module>
        <module>spring-boot-starter-im</module>
        <module>spring-boot-starter-ocr</module>
        <module>spring-boot-starter-finance</module>
        <module>spring-boot-starter-trade</module>
        <module>spring-boot-starter-wechat</module>
        <module>spring-boot-starter-sms</module>
        <module>spring-boot-starter-excel</module>
        <module>spring-boot-starter-system</module>
        <module>spring-boot-starter-contract</module>
        <module>spring-boot-starter-web</module>
        <module>spring-boot-starter-security</module>
        <module>spring-boot-starter-cache</module>
        <module>spring-boot-starter-job</module>
    </modules>
</project>
