<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-cache</artifactId>
        <version>1.1.8.RELEASE</version>
    </parent>

    <artifactId>spring-boot-starter-cache-biz</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Cache API -->
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-cache-api</artifactId>
            <version>1.1.8.RELEASE</version>
        </dependency>

        <!-- Spring Boot Redis Dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <!-- Spring Boot Dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Lombok for boilerplate code reduction -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

</project>