-- 用户账单结算记录（按订单商品行）
CREATE TABLE IF NOT EXISTS `dist_user_bill_settle_record` (
  `id` varchar(64) NOT NULL COMMENT '主键ID',
  `seq_no` int NULL DEFAULT NULL COMMENT '序列编号',
  `org_code` varchar(64) NULL DEFAULT NULL COMMENT '机构编码',
  `update_by` varchar(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `create_by` varchar(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `version` varchar(10) NULL DEFAULT NULL COMMENT '乐观锁版本号',
  `deleted` varchar(10) NULL DEFAULT '0' COMMENT '逻辑删除 0-未删 1-已删',
  `dist_user_bill_settle_record_code` varchar(60) NOT NULL COMMENT '结算记录流水编码',
  `dist_biz_line_code` varchar(32) NOT NULL COMMENT '业务线编码',
  `dist_payer_user_code` varchar(64) NOT NULL COMMENT '付款用户编码',
  `td_od_sys_user_code` varchar(64) NULL DEFAULT NULL COMMENT '下单人用户编码（冗余）',
  `td_od_sys_user_real_name` varchar(100) NULL DEFAULT NULL COMMENT '下单人姓名（冗余）',
  `td_od_gd_code` varchar(64) NOT NULL COMMENT '订单商品编码',
  `td_gd_code` varchar(64) NULL DEFAULT NULL COMMENT '商品编码',
  `td_gd_name` varchar(200) NULL DEFAULT NULL COMMENT '商品名称',
  `td_gd_commission_rate` decimal(8, 4) NOT NULL DEFAULT 0.9000 COMMENT '分佣比例（冗余）',
  `dist_paid_amount` decimal(18, 2) NOT NULL DEFAULT 0.00 COMMENT '付费金额',
  `dist_commission_pool_amount` decimal(18, 2) NOT NULL DEFAULT 0.00 COMMENT '分佣池金额（付费×商品分佣比例）',
  `dist_inviter_user_code` varchar(64) NULL DEFAULT NULL COMMENT '直推邀请人用户编码',
  `dist_inviter_commission_amount` decimal(18, 2) NOT NULL DEFAULT 0.00 COMMENT '直推邀请人分佣金额',
  `dist_superior_inviter_user_code` varchar(64) NULL DEFAULT NULL COMMENT '上级邀请人用户编码',
  `dist_superior_commission_amount` decimal(18, 2) NOT NULL DEFAULT 0.00 COMMENT '上级邀请人分佣金额（付费5%）',
  `dist_commission_applied_status_code` varchar(32) NOT NULL DEFAULT 'NO' COMMENT '分佣是否已计入汇总 YES-是 NO-否',
  `dist_settled_status_code` varchar(32) NOT NULL DEFAULT 'NO' COMMENT '是否结算完成 YES-是 NO-否',
  `dist_settle_applied_status_code` varchar(32) NOT NULL DEFAULT 'NO' COMMENT '是否申请结算 YES-是 NO-否',
  `dist_in_service_status_code` varchar(32) NOT NULL DEFAULT 'NO' COMMENT '是否在服务期内 YES-是 NO-否',
  `dist_service_period_end_at` datetime NULL DEFAULT NULL COMMENT '服务期结束时间',
  `dist_settled_at` datetime NULL DEFAULT NULL COMMENT '实际结算时间',
  `dist_settle_batch_code` varchar(60) NULL DEFAULT NULL COMMENT '结算批次编码',
  `dist_settle_batch_status_code` varchar(32) NULL DEFAULT NULL COMMENT '结算批次状态（冗余）YES-已完成 NO-未完成',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_dist_bill_settle_od_gd`(`td_od_gd_code`),
  INDEX `idx_dist_bill_settle_payer`(`dist_payer_user_code`, `dist_settled_status_code`),
  INDEX `idx_dist_bill_settle_batch`(`dist_settle_batch_code`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '用户账单结算记录';
