-- AI 消耗明细表
CREATE TABLE IF NOT EXISTS `ai_usage_record` (
  `id` varchar(64) NOT NULL COMMENT '主键ID',
  `seq_no` int NULL DEFAULT NULL COMMENT '序列编号',
  `org_code` varchar(64) NULL DEFAULT NULL COMMENT '机构编码',
  `update_by` varchar(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `create_by` varchar(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `version` varchar(10) NULL DEFAULT NULL COMMENT '乐观锁版本号',
  `deleted` varchar(10) NULL DEFAULT '0' COMMENT '逻辑删除 0-未删 1-已删',
  `ai_usage_record_code` varchar(64) NOT NULL COMMENT '消耗明细业务编码',
  `user_code` varchar(64) NOT NULL COMMENT '用户编码',
  `ai_agent_code` varchar(64) NOT NULL COMMENT '智能体业务编码',
  `ai_api_config_code` varchar(64) NOT NULL COMMENT 'AI 接口配置编码',
  `ai_chat_session_code` varchar(64) NULL DEFAULT NULL COMMENT '会话业务编码',
  `ai_usage_record_model` varchar(128) NULL DEFAULT NULL COMMENT '使用的模型',
  `ai_usage_record_prompt_tokens` int NULL DEFAULT NULL COMMENT '提示词 token 数',
  `ai_usage_record_completion_tokens` int NULL DEFAULT NULL COMMENT '回复 token 数',
  `ai_usage_record_total_tokens` int NULL DEFAULT NULL COMMENT '总 token 数',
  `ai_usage_record_input_unit_price` decimal(18,8) NULL DEFAULT NULL COMMENT '输入单价快照（每1K tokens，元）',
  `ai_usage_record_output_unit_price` decimal(18,8) NULL DEFAULT NULL COMMENT '输出单价快照（每1K tokens，元）',
  `ai_usage_record_total_price` decimal(18,6) NULL DEFAULT NULL COMMENT '本次消耗总价（元）',
  `ai_usage_record_success_code` varchar(8) NULL DEFAULT NULL COMMENT '是否成功：1-成功 0-失败',
  `ai_usage_record_error_message` varchar(1024) NULL DEFAULT NULL COMMENT '错误信息',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_ai_usage_record_code`(`ai_usage_record_code` ASC) USING BTREE,
  INDEX `idx_ai_usage_record_user`(`user_code` ASC) USING BTREE,
  INDEX `idx_ai_usage_record_agent`(`ai_agent_code` ASC) USING BTREE,
  INDEX `idx_ai_usage_record_create_time`(`create_time` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = 'AI 消耗明细' ROW_FORMAT = DYNAMIC;
