<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-wechat</artifactId>
        <version>3.5.5</version>
    </parent>

    <artifactId>spring-boot-starter-wechat-biz</artifactId>
    <packaging>jar</packaging>

    <properties>
        <weixin-java-mp.version>4.6.0</weixin-java-mp.version>
        <weixin-java-miniapp.version>4.6.0</weixin-java-miniapp.version>
        <weixin-java-open.version>4.6.0</weixin-java-open.version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <hutool-all.version>5.3.8</hutool-all.version>
    </properties>


    <dependencies><!-- https://mvnrepository.com/artifact/com.google.guava/guava -->


        <!-- weixin-java-mp SDK框架-->
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-mp</artifactId>
            <version>${weixin-java-mp.version}</version>
        </dependency>

        <!--微信小程序 -->
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-miniapp</artifactId>
            <version>${weixin-java-miniapp.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-open</artifactId>
            <version>${weixin-java-open.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool.version}</version>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-system-api</artifactId>
            <version>3.5.5</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-data-api</artifactId>
            <version>3.5.5</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-wechat-api</artifactId>
            <version>3.5.5</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-web-api</artifactId>
        </dependency>

    </dependencies>
</project>
