<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-contract-biz</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>TG-boot 合同/电子签章 业务实现模块</description>
    <url>https://github.com/modulepub/tg-boot.git</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
            <comments>Permissive open source license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>panzhen</id>
            <name>panzhen</name>
            <email>panzhen@mail.module.pub</email>
            <url>https://github.com/modulepub/tg-boot.git</url>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git@github.com:modulepub/tg-boot.git</connection>
        <developerConnection>scm:git@github.com:modulepub/tg-boot.git</developerConnection>
        <url>https://github.com/modulepub/tg-boot.git</url>
        <tag>3.5.0</tag>
    </scm>
    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-contract</artifactId>
        <version>3.5.0</version>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <tars.version>1.0.3</tars.version>
        <httpclient.version>4.4.1</httpclient.version>
        <fastjson.version>1.2.41</fastjson.version>
        <itextpdf.version>7.0.3</itextpdf.version>

    </properties>
    <!-- 基础模块 -->

    <dependencies>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-contract-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ancun.netsign</groupId>
            <artifactId>netsign-sdk</artifactId>
            <version>3.0.6</version>
        </dependency>


        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>



        <!-- json begin -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${fastjson.version}</version>
        </dependency>
        <!-- json end -->

        <!-- httpclient begin -->
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>${httpclient.version}</version>
        </dependency>
        <!-- httpclient end -->

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.3.2</version>
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
            <version>5.5.13</version>
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>kernel</artifactId>
            <version>${itextpdf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>io</artifactId>
            <version>${itextpdf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>layout</artifactId>
            <version>${itextpdf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-web-api</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}-${project.version}</finalName>
        <resources>
            <resource>
                <filtering>false</filtering> <!-- 核心：关闭过滤 -->
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.json</include>
                    <include>**/*.ftl</include>
                </includes>
            </resource>
            <resource>
                <filtering>false</filtering> <!-- 核心：关闭过滤 -->
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/**/*</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>
