<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-contract-biz</artifactId>
    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-contract</artifactId>
        <version>1.1.8.RELEASE</version>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <tars.version>1.0.3</tars.version>
        <httpclient.version>4.4.1</httpclient.version>
        <fastjson.version>1.2.41</fastjson.version>
        <itextpdf.version>7.0.3</itextpdf.version>

    </properties>
    <!-- 基础模块 -->

    <dependencies>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-contract-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ancun.netsign</groupId>
            <artifactId>netsign-sdk</artifactId>
            <version>3.0.6</version>
            <scope>system</scope>
            <systemPath>${project.basedir}\lib\netsign-sdk-3.0.6.mix.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        <!-- json begin -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${fastjson.version}</version>
        </dependency>
        <!-- json end -->

        <!-- httpclient begin -->
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>${httpclient.version}</version>
        </dependency>
        <!-- httpclient end -->

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.3.2</version>
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
            <version>5.5.13</version>
        </dependency>

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>kernel</artifactId>
            <version>${itextpdf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>io</artifactId>
            <version>${itextpdf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>layout</artifactId>
            <version>${itextpdf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-web-api</artifactId>
        </dependency>
    </dependencies>
</project>