<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-security-api</artifactId>

    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>TG-boot 安全 API接口模块</description>
    <url>https://github.com/modulepub/tg-boot.git</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
            <comments>Permissive open source license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>panzhen</id>
            <name>panzhen</name>
            <email>panzhen@mail.module.pub</email>
            <url>https://github.com/modulepub/tg-boot.git</url>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git@github.com:modulepub/tg-boot.git</connection>
        <developerConnection>scm:git@github.com:modulepub/tg-boot.git</developerConnection>
        <url>https://github.com/modulepub/tg-boot.git</url>
        <tag>3.5.1</tag>
    </scm>

    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-security</artifactId>
        <version>3.5.2</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-cache-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-data-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <!-- Spring Security 核心依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        
        <!-- Spring Web 依赖（提供 Servlet API） -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
        </dependency>

        <!-- BouncyCastle 扩展包（Hutool SM2 辅助依赖） -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
        </dependency>
        <!-- JWT 支持 -->
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
        </dependency>
        

        
        <!-- Spring Boot Configuration Processor -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-web-api</artifactId>
            <version>${project.version}</version>
        </dependency>


    </dependencies>
</project>
