server:
  undertow:
    decode-url: true
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
  port: 9999
  servlet:
    context-path:
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #json 时间戳统一转换
  Jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    open-in-view: false
  aop:
    proxy-target-class: true
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=10000,expireAfterWrite=10m
  #freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl 文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
    #Spring Boot 2.6+后映射匹配的默认策略已从AntPathMatcher更改为PathPatternParser,需要手动指定为ant-path-matcher
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude:
      # 如果不需要MongoDB，可以取消注释下面这行来禁用MongoDB自动配置
      # - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    url: jdbc:h2:file:./data/tg_boot;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=VALUE,VERSION;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      # 关闭固定 SQL 文件初始化，改由实体类自动建表
      mode: always
      encoding: UTF-8
      continue-on-error: false
      schema-locations:
        - optional:file:./data/init/data_tg_v3.5.1.2.sql
  h2:
    console:
      enabled: true
      path: /pub/h2-console

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:pub/module/**/xml/*Mapper.xml
  type-aliases-package: pub.module.**.entity
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
logging:
  level:
    pub.module.*: debug
    org.springframework.boot.autoconfigure: INFO
# 代码生成
gen:
  # 作者
  author: tg
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: pub.module.system
  # 模块名称
  moduleName: system
  # 是否允许生成文件覆盖到本地（自定义路径），默认不允许
  allowOverwrite: true

