server:
  undertow:
    decode-url: true
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
  port: 9999
  servlet:
    context-path:
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #json 时间戳统一转换
  Jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    open-in-view: false
  aop:
    proxy-target-class: true
  #freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl 文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
    #Spring Boot 2.6+后映射匹配的默认策略已从AntPathMatcher更改为PathPatternParser,需要手动指定为ant-path-matcher
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude:
      # 如果不需要MongoDB，可以取消注释下面这行来禁用MongoDB自动配置
      # - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    url: jdbc:mysql://v.com:3306/tg?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: tg
    password: xaw6CB251EbDQ22n
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 9
      host: v.com
      port: 6379
      password:
      timeout: 30000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:pub/module/**/xml/*Mapper.xml
  type-aliases-package: pub.module.**.entity
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
logging:
  level:
    pub.module.*: debug
    org.springframework.boot.autoconfigure: INFO



wechat:
  mini:
    appid: xx
    appSecret: d248ab6a0f4d7572af26018973c77e54
    msgDataFormat: JSON
    mchId: 1667446017
    mchKey: xx
    privateKeyPath: classpath:apiclient_key.pem
    privateCertPath: classpath:apiclient_cert.pem
    notify-url: https://xxx/jeecg-boot/wechat/parseOrderNotifyResult
    subAppId:
    subMchId:

## >>>>>>FILE模块上传配置 BEGIN
upload:
  urlPrefix: https://oss.xx.net
  # 文件上传方式，可选项：local（本地）、minio（minio）、aliOss（阿里云OSS）
  type: aliOss
  local:
    path: /opt/upFiles
    # minio文件上传
  minio:
    minioUrl: http://192.168.0.1:9090
    minioName: minioadmin
    minioPass: minioadmin
    bucketName: tg
  aliOss:
    accessKey: LTAI5tAX24LHf3PQEcSiQgNA
    secretKey: c9ExQbzp0ia6E95LlJiT7DUyf91SJa
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: matchlove

aq:
  url: https://oapi.asign.cn
  # 修正核心：移除每个app对象末尾多余的 }，保持缩进式对象的纯净格式
  apps:
    - appId: "73081641"
      privateKey: "xxxxdS6ja/G8//s398eSCRuM/3lSnerBYjXwDPN4ccgLA/80EkDj9uQ/oRNpejpsK62xW5NFHwHgWO8pIm7Hy2bBbdfs87nDG0eOqtR+wjVaMx1CtBJ0BvCUbgb9papu45EkfiHYiGK4EGkeqeS3hSX/HAgMBAAECggEALgsP4L3rx5kDZ7w8k9rE01fr6FG3SsvgYv/aqVx4KN4ZRWnJ5LI4e/8dw+uWa6vYkXYmfV9YZqGDOo3wADGHCuXbRAH+A6EMKS3Frrcqu8H62GQeFuakqjc66Tpg6cGTLHxPBgtnX2w8Edwt7nbZDpm5AIRZF+B4ofmLd1U74G4aB/LsDoIHcayC7v3M4STXsOn4RWvRyF7ZImtlU1tWNUu7WZq1GBzi+dCakz4HSIfHdFm39qQOMpC5B8pM0uqa6FfPO4t1RTiUn0A5JMEs4pGOq0sV/mkVvhCuwpRrj8isMSDOjXI0XRmNZwOL/ChsrqhPKXBfLlPOizLdBVKnAQKBgQD1vXp0ne3lwbvaXeq4x2QxIV6ycVoWXdIr+eG+JZigtuR7vaE0sqHAIYQyAAiULUArWkYnyN7O8o5mxwqf2xVSYiN5qoHWDsCUBmSfkvU8NvhqTe0G1bXGK1MKSVO1BWeGVstgVlGvi5MxBvl1EpEJ23tkLMFI3BF0GCJaUSFglwKBgQDzAWSv0vPoppa4Hxqxe0w/Yo55sVVdDovUQuXy9ITrBmj+5Ax8UzrqffNBY0lzg3XbDYgK3dtEJ0mdsbr8CJW1hjISrfkdgPQhXTEMQo7FcZ9Da5EkGBMCSKLmAGn0Z3fvMHHrzcF/jM6GxinZPPTfgG4A+9d2R8wYJJjXM2OQUQKBgQDnvS68yK4vDDrF2+ldJZODjW+LIcAN9Z4coIJU2YmMjcz8MEDUvFwzHqhWqpdsfRvVhkVAgXo0eKL3o16Oj4EU9r1zn+re3XyYW0sK/QBNL52mSiRrXKAV6Idf3PSWcilFk5YpHF3eCObexi/7Sm4CeLttJZOEzRuceqHywC2UswKBgArQ5A9jX1HaoFi/oauGpmUn2NmXyAnlTNn8xEllEsl3NpMpyVh7R+MKChq99ZX7ovJGDukU6N6GtSMctwriwu8acv4b2juy8qrNgBJgoAQvw3v3vLUTkT0HyKBeIlkrhc4SpO9u8A7iUIr1JQWzTd7o03yduQBdv7rPXjIt6l+RAoGBAN/+g1z39QozxXd72JwBQ2uf4voqYml1Iz23pHUmaNGAEUYG8y70L3TgkRKwOBpNhzjAtSmTlY6Uubc5mwpX1Eo91VEZbENB9wfglnL/R6OwgAoIPeNLgZvOYvMMkw3fC/rwpkzVnkQbhI9TiHeQ/SJ/Mq1T5z/V6/Cy4Wth/gTN"
    - appId: "22825332"
      privateKey: "xx+9"
# 代码生成
gen:
  # 作者
  author: tg
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: pub.module.customer
  # 模块名称
  moduleName: customer
  # 是否允许生成文件覆盖到本地（自定义路径），默认不允许
  allowOverwrite: true

