<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-security-biz</artifactId>

    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>TG-boot 安全 业务实现模块</description>
    <url>https://github.com/modulepub/tg-boot.git</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
            <comments>Permissive open source license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>panzhen</id>
            <name>panzhen</name>
            <email>panzhen@mail.module.pub</email>
            <url>https://github.com/modulepub/tg-boot.git</url>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git@github.com:modulepub/tg-boot.git</connection>
        <developerConnection>scm:git@github.com:modulepub/tg-boot.git</developerConnection>
        <url>https://github.com/modulepub/tg-boot.git</url>
        <tag>3.5.3</tag>
    </scm>

    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-security</artifactId>
        <version>3.5.3</version>
    </parent>

    <dependencies>
        <!-- API模块 -->
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-security-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <!-- System模块依赖（用于访问用户和权限服务） -->
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-system-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- Spring Security -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-jose</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-cache-api</artifactId>
            <version>${project.version}</version>
        </dependency>



    </dependencies>
</project>
