<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-components</artifactId>
        <version>3.5.1</version>
    </parent>



    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-generator</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>TG-boot 代码生成器组件聚合</description>
    <url>https://github.com/modulepub/tg-boot.git</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
            <comments>Permissive open source license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>panzhen</id>
            <name>panzhen</name>
            <email>panzhen@mail.module.pub</email>
            <url>https://github.com/modulepub/tg-boot.git</url>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git@github.com:modulepub/tg-boot.git</connection>
        <developerConnection>scm:git@github.com:modulepub/tg-boot.git</developerConnection>
        <url>https://github.com/modulepub/tg-boot.git</url>
        <tag>3.5.1</tag>
    </scm>
    <properties>
        <!-- 跳过部署到远程仓库（Sonatype） -->
        <maven.deploy.skip>false</maven.deploy.skip>
        <!-- 跳过安装到本地仓库（可选，如需本地使用可注释） -->
        <!-- <maven.install.skip>true</maven.install.skip> -->
        <!-- 跳过Spring Boot胖JAR打包（仅保留普通JAR） -->
        <spring-boot.repackage.skip>false</spring-boot.repackage.skip>
    </properties>
    <modules>
        <module>spring-boot-starter-generator-biz</module>
        <module>spring-boot-starter-generator-api</module>
    </modules>
</project>
