-- 微信公众号配置（后台维护，启动/刷新时加载到 WxMpService）
CREATE TABLE IF NOT EXISTS `wx_mp_config` (
  `id` varchar(64) NOT NULL COMMENT '主键ID',
  `wx_mp_config_code` varchar(64) NOT NULL COMMENT '配置编码（业务主键）',
  `wx_mp_config_name` varchar(128) DEFAULT NULL COMMENT '配置名称',
  `wx_mp_config_app_id` varchar(64) NOT NULL COMMENT '公众号 AppId',
  `wx_mp_config_app_secret` varchar(128) NOT NULL COMMENT '公众号 AppSecret',
  `wx_mp_config_token` varchar(128) DEFAULT NULL COMMENT '消息校验 Token',
  `wx_mp_config_aes_key` varchar(128) DEFAULT NULL COMMENT '消息加解密密钥 EncodingAESKey',
  `wx_mp_config_enabled_status_code` varchar(8) DEFAULT '1' COMMENT '启用状态：0-否 1-是',
  `wx_mp_config_menu_json` mediumtext COMMENT '自定义菜单 JSON（button 数组）',
  `wx_mp_config_menu_published_time` datetime DEFAULT NULL COMMENT '菜单最近发布时间',
  `wx_mp_config_ai_agent_code` varchar(64) DEFAULT NULL COMMENT '接管回复的 AI 智能体编码',
  `wx_mp_config_ai_auto_reply_status_code` varchar(8) DEFAULT '0' COMMENT 'AI 自动回复：0-否 1-是',
  `wx_mp_config_subscribe_reply_status_code` varchar(8) DEFAULT '0' COMMENT '关注回复：0-否 1-是',
  `wx_mp_config_subscribe_reply_json` mediumtext COMMENT '关注回复图文 JSON（title/description/picUrl/url）',
  `wx_mp_config_remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `org_code` varchar(64) DEFAULT NULL,
  `version` varchar(32) DEFAULT NULL,
  `seq_no` bigint DEFAULT NULL,
  `deleted` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wx_mp_config_code` (`wx_mp_config_code`),
  KEY `idx_wx_mp_config_app_id` (`wx_mp_config_app_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信公众号配置';
