<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-ai-api</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>TG-boot AI API 接口模块</description>

    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-ai</artifactId>
        <version>${revision}</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-common</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
