<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-components</artifactId>
        <version>3.5.1</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-file</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>TG-boot 文件组件聚合</description>
    <url>https://github.com/modulepub/tg-boot.git</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
            <comments>Permissive open source license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>panzhen</id>
            <name>panzhen</name>
            <email>panzhen@mail.module.pub</email>
            <url>https://github.com/modulepub/tg-boot.git</url>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git@github.com:modulepub/tg-boot.git</connection>
        <developerConnection>scm:git@github.com:modulepub/tg-boot.git</developerConnection>
        <url>https://github.com/modulepub/tg-boot.git</url>
        <tag>3.5.1</tag>
    </scm>

    <modules>
        <module>spring-boot-starter-file-biz</module>
        <module>spring-boot-starter-file-api</module>
    </modules>
</project>
