<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-starter-log-biz</artifactId>

    <packaging>jar</packaging>

    <parent>
        <groupId>pub.module</groupId>
        <artifactId>spring-boot-starter-log</artifactId>
        <version>1.1.8.RELEASE</version>
    </parent>

    <dependencies>
        <!-- API模块 -->
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-security-api</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        
        <!-- System模块依赖（用于访问用户和权限服务） -->
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-system-api</artifactId>
        </dependency>
        <!-- Data模块依赖（用于MyBatis-Plus） -->
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-data-api</artifactId>
        </dependency>
        <!-- Spring Security -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-jose</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-cache-api</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>
        <dependency>
            <groupId>pub.module</groupId>
            <artifactId>spring-boot-starter-web-api</artifactId>
        </dependency>


    </dependencies>
</project>